apiVersion: v1
kind: Service
metadata:
  name: alertmanager-label-enricher
  labels:
    app.kubernetes.io/name: alertmanager-label-enricher
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9099
      targetPort: http
  selector:
    app.kubernetes.io/name: alertmanager-label-enricher
