{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "alertmanager-label-enricher.fullname" . }}
  labels:
    {{- include "alertmanager-label-enricher.labels" . | nindent 4 }}
rules:
  {{- $rules := .Values.rbac.rules }}
  {{- if .Values.crd.enabled }}
  {{- $rules = concat $rules (list
        (dict "apiGroups" (list "enricher.splattner.github.io") "resources" (list "enrichmentrules") "verbs" (list "get" "list" "watch"))
        (dict "apiGroups" (list "") "resources" (list "namespaces") "verbs" (list "get" "list" "watch"))
      ) }}
  {{- end }}
  {{- toYaml $rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "alertmanager-label-enricher.fullname" . }}
  labels:
    {{- include "alertmanager-label-enricher.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "alertmanager-label-enricher.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "alertmanager-label-enricher.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
